- hosts: localhost
  become: yes
  #become_user: azureuser
  #  #connection: local
  become_user: root
  #      #ask_become_pass: true
  #       # remote_user: azureuser
  roles:
    - role: postgres
    - role: sonarqube
  
